sources:
  - name: mk_mall
    database: sourcedb
    schema: mk_mall
    tables:
      - name: nations
      - name: regions
      - name: customers
      - name: suppliers
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 5, period: day}